version: '3'
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      DB_HOST: db
    depends_on:
      - db
    restart: always
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: api_webshop
      MYSQL_PASSWORD: pwd
      MYSQL_ROOT_PASSWORD: pwd
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - dbdata:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
    ports:
      - "8181:80"
    depends_on:
      - db
    restart: always
volumes:
  dbdata:
